FROM centos:latest
MAINTAINER "The CentOS Project" <admin@jiobxn.com>
ARG LATEST="0"

RUN yum clean all; yum -y update; yum -y install net-tools cronie; yum clean all

COPY ./redis /redis

RUN ln -s /redis/bin/* /usr/local/bin/

VOLUME /redis/data

COPY redis.sh /redis.sh
RUN chmod +x /redis.sh

ENTRYPOINT ["/redis.sh"]

EXPOSE 6379

CMD ["redis-server", "/redis/redis.conf"]

# docker build -t redis .
# docker run -d --restart unless-stopped -v /docker/redis:/redis/data -p 6379:6379  -e REDIS_PASS=bigpass --name redis redis
