FROM centos:latest
MAINTAINER "The CentOS Project" <admin@jiobxn.com>
ARG LATEST="0"

RUN curl -s https://openresty.org/package/centos/openresty.repo >/etc/yum.repos.d/openresty.repo
RUN yum clean all; yum -y install epel-release; yum -y update; yum -y install openresty openresty-resty openresty-resty keepalived wget net-tools iproute ipset iptables cronie; yum clean all

RUN cd /mnt \
    && wget -c https://github.com/jiobxn/VeryNginx/archive/master.zip -O VeryNginx.zip \
    && unzip VeryNginx.zip \
    && mv VeryNginx-master/verynginx/ /usr/local/openresty/ \
    && chown -R nobody.nobody /usr/local/openresty/verynginx/ \
    && ln -s /usr/local/openresty/ /opt/verynginx \
    && rm -rf VeryNginx*

VOLUME /usr/local/openresty/nginx/html /usr/local/openresty/nginx/logs /key

COPY openresty.sh /openresty.sh
RUN chmod +x /openresty.sh

ENTRYPOINT ["/openresty.sh"]

EXPOSE 80 443

CMD ["openresty", "-g", "daemon off;"]

# docker build -t openresty .
# docker run -d --cap-add NET_ADMIN -p 9999:80 -e WAF=Y -e WAF_REQ="404,20;403,10" --name openresty jiobxn/nginx:waf
