FROM centos:latest
MAINTAINER "The CentOS Project" <admin@jiobxn.com>
ARG LATEST="0"

RUN rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
RUN yum clean all; yum -y install epel-release; yum -y update; yum -y install nginx keepalived net-tools iproute; yum clean all

VOLUME /var/log/nginx

COPY l4pxy.sh /l4pxy.sh
RUN chmod +x /l4pxy.sh

ENTRYPOINT ["/l4pxy.sh"]

CMD ["L4PXY"]

# docker build -t l4pxy .
# docker run -itd --cap-add net_admin --network mynetwork --ip 192.168.1.38 -e L4PXY="8443|192.168.2.91:443;192.168.1.39:53|1.1.1.1:53&weight=5,9.9.9.9:53&weight=10%udp=Y" --name l4pxy jiobxn/l4pxy
