FROM alpine:latest
MAINTAINER "The Alpine Project" <admin@jiobxn.com>
ARG LATEST="0"

RUN apk update && apk add openvpn openssl mtr tzdata bash && rm -rf /var/cache/apk/*

VOLUME /key

WORKDIR /key

ENTRYPOINT ["openvpn", "--config", "client.ovpn"]

# docker build -t ovpn .
# docker run -d --restart unless-stopped --cap-add NET_ADMIN --device /dev/net/tun --network host -v /docker/ovpn:/key --name ovpn ovpn
