FROM alpine:latest
MAINTAINER "The Alpine Project" <admin@jiobxn.com>
ARG LATEST="0"

RUN apk update --no-cache && apk add openjdk8 nmap-ncat at curl tzdata bash --no-cache

RUN cd /mnt \
        && wget -c https://apache.org/dist/zookeeper/stable/$(curl -s https://apache.org/dist/zookeeper/stable/ |grep tar.gz |awk -F\" 'NR==1{print $6}') \
        && tar zxf apache-zookeeper-*.tar.gz \
        && \rm apache-zookeeper-*.tar.gz \
        && mv apache-zookeeper-* /zookeeper

VOLUME /zookeeper/data

COPY zookeeper.sh /zookeeper.sh
RUN chmod +x /zookeeper.sh

WORKDIR /zookeeper

ENTRYPOINT ["/zookeeper.sh"]

EXPOSE 2181

CMD ["bin/zkServer.sh", "start-foreground"]

# docker build -t zookeeper .
# docker run -d --restart unless-stopped -p 2181:2181 -v /docker/zookeeper:/zookeeper/data --name zookeeper zookeeper
