FROM centos:7
MAINTAINER "The CentOS Project" <admin@jiobxn.com>
ARG LATEST="0"

RUN curl -s http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest |egrep 'CN\|ipv4' |awk -F'|' '{printf("%s/%d \n", $4, 32-log($5)/log(2))}' >/etc/chnroute.txt
RUN curl -s https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo -o /etc/yum.repos.d/librehat-shadowsocks-epel-7.repo
RUN yum clean all; yum -y install epel-release; yum -y update \
        && yum -y install net-tools iproute iptables openssl shadowsocks-libev ipset ipset-libs \
        && yum clean all

VOLUME /key

COPY ssserver.sh /ssserver.sh
RUN chmod +x /ssserver.sh

EXPOSE 8443

ENTRYPOINT ["/ssserver.sh"]

CMD ["shadowsocks"]

# docker build -t shadowsocks .
# docker run -d --restart always -p 8443:8443 --hostname shadowsocks --name shadowsocks shadowsocks
